import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import aiProfilePic2 from "../../public/images/profile/aiProfilePic2.jpeg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import Transition from "@/components/Transition";

export default function Home() {
  return (
    <>
      <Head>
        <title>Abhishek Goswami - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transition />
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0 md:pt-16 sm:pt-8 xs:!pt-0">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={aiProfilePic2}
                alt="Abhishek Goswami"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className="w-1/2 flex flex-col ml-8 items-center self-center lg:w-full lg:text-center">
              {/* <h1></h1> */}
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="mb-1 xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="text-justify my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Abhishek_Goswami_YoP_2024 resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-white hover:text-dark border border-solid border-transparent hover:border-dark md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  résumé <LinkArrow className={"w-5 ml-1"} />
                </Link>
                {/* <Link href="mailto:myselfabhi27@gmail.com" target={"_blank"}>
                  Contact me
                </Link> */}
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image
            src={lightBulb}
            alt="Abhishek Goswami"
            className="w-full h-auto"
          />
        </div>
      </main>
    </>
  );
}
